import json
import os
from app import create_app, Config
from models import db, Category, Tool

CATEGORIES = [
    {
        "name": "Text & Writing",
        "slug": "text-writing",
        "icon": "fa-pen-fancy",
        "description": "AI-powered tools for content creation, copywriting, and text generation.",
    },
    {
        "name": "Image Generation",
        "slug": "image-generation",
        "icon": "fa-image",
        "description": "Create stunning images, art, and visuals using artificial intelligence.",
    },
    {
        "name": "Code & Development",
        "slug": "code-development",
        "icon": "fa-code",
        "description": "AI assistants that help you write, debug, and ship code faster.",
    },
    {
        "name": "Video & Audio",
        "slug": "video-audio",
        "icon": "fa-video",
        "description": "AI tools for video editing, audio generation, and multimedia production.",
    },
    {
        "name": "Productivity",
        "slug": "productivity",
        "icon": "fa-bolt",
        "description": "Boost your workflow with AI-powered productivity and organization tools.",
    },
    {
        "name": "Data & Analytics",
        "slug": "data-analytics",
        "icon": "fa-chart-bar",
        "description": "Extract insights from data using AI-driven analytics platforms.",
    },
    {
        "name": "Design",
        "slug": "design",
        "icon": "fa-palette",
        "description": "AI-enhanced design tools for UI/UX, graphics, and creative work.",
    },
    {
        "name": "Customer Support",
        "slug": "customer-support",
        "icon": "fa-headset",
        "description": "AI chatbots and support tools to automate and enhance customer service.",
    },
]

TOOLS = [
    # ── Text & Writing ──
    {
        "name": "ChatGPT",
        "slug": "chatgpt",
        "tagline": "The AI assistant that started it all",
        "description": "OpenAI's conversational AI powered by GPT-4. Handles writing, analysis, coding, math reasoning, and multimodal tasks including image understanding. The most widely adopted AI assistant globally.",
        "features": [
            "Multi-turn conversation",
            "Code generation & debugging",
            "Image understanding",
            "Plugin ecosystem",
            "Custom GPTs",
            "Web browsing",
        ],
        "pricing": "Freemium",
        "pricing_details": "Free with GPT-3.5. Plus at $20/mo for GPT-4. Team at $25/user/mo.",
        "website_url": "https://chat.openai.com",
        "rating": 4.8,
        "review_count": 15200,
        "is_featured": True,
        "category_slug": "text-writing",
    },
    {
        "name": "Claude",
        "slug": "claude",
        "tagline": "Thoughtful AI for nuanced tasks",
        "description": "Anthropic's Claude excels at long-form analysis, careful reasoning, and following complex instructions. Known for its 200K context window and nuanced, honest responses with strong safety alignment.",
        "features": [
            "200K context window",
            "Document analysis",
            "Structured data extraction",
            "Code generation",
            "Artifacts for live content",
            "Multi-language support",
        ],
        "pricing": "Freemium",
        "pricing_details": "Free tier available. Pro at $20/mo for higher limits and Claude 3.5 Sonnet.",
        "website_url": "https://claude.ai",
        "rating": 4.7,
        "review_count": 8400,
        "is_featured": True,
        "category_slug": "text-writing",
    },
    {
        "name": "Jasper",
        "slug": "jasper",
        "tagline": "Enterprise-grade AI content platform",
        "description": "Jasper is built for marketing teams to create on-brand content at scale. Offers brand voice settings, campaign workflows, and deep integrations with marketing stacks.",
        "features": [
            "Brand voice customization",
            "Campaign management",
            "SEO optimization",
            "Template library",
            "Team collaboration",
            "Analytics dashboard",
        ],
        "pricing": "Paid",
        "pricing_details": "Creator at $49/mo. Pro at $69/mo. Business plans custom-priced.",
        "website_url": "https://jasper.ai",
        "rating": 4.4,
        "review_count": 5200,
        "is_featured": False,
        "category_slug": "text-writing",
    },
    {
        "name": "Copy.ai",
        "slug": "copy-ai",
        "tagline": "AI copywriting for go-to-market teams",
        "description": "Copy.ai provides AI-powered workflows for sales, marketing, and operations. Automates content creation across emails, social posts, landing pages, and more with pre-built workflows.",
        "features": [
            "GTM AI workflows",
            "Sales copy generation",
            "Email sequences",
            "Social media content",
            "API access",
            "90+ templates",
        ],
        "pricing": "Freemium",
        "pricing_details": "Free for 2000 words/mo. Pro at $49/mo. Enterprise custom pricing.",
        "website_url": "https://copy.ai",
        "rating": 4.3,
        "review_count": 3800,
        "is_featured": False,
        "category_slug": "text-writing",
    },
    # ── Image Generation ──
    {
        "name": "Midjourney",
        "slug": "midjourney",
        "tagline": "Artistic image generation at its finest",
        "description": "Midjourney produces highly artistic, visually striking images from text prompts. Known for its aesthetic quality, style range, and active community. Operates primarily through Discord with a web interface in development.",
        "features": [
            "High aesthetic quality",
            "Style tuning",
            "Image variation & upscaling",
            "Pan and zoom",
            "Character reference",
            "Style reference",
        ],
        "pricing": "Paid",
        "pricing_details": "Basic $10/mo (200 images). Standard $30/mo. Pro $60/mo. Mega $120/mo.",
        "website_url": "https://midjourney.com",
        "rating": 4.7,
        "review_count": 11000,
        "is_featured": True,
        "category_slug": "image-generation",
    },
    {
        "name": "DALL-E 3",
        "slug": "dall-e-3",
        "tagline": "OpenAI's text-to-image model",
        "description": "DALL-E 3 generates highly detailed images from natural language descriptions. Integrated into ChatGPT, it excels at following complex prompts accurately and rendering text within images.",
        "features": [
            "Precise prompt following",
            "Text rendering in images",
            "ChatGPT integration",
            "Inpainting & outpainting",
            "Safety filters",
            "API access",
        ],
        "pricing": "Freemium",
        "pricing_details": "Included with ChatGPT Plus ($20/mo). API pricing per image.",
        "website_url": "https://openai.com/dall-e-3",
        "rating": 4.5,
        "review_count": 7600,
        "is_featured": False,
        "category_slug": "image-generation",
    },
    {
        "name": "Stable Diffusion",
        "slug": "stable-diffusion",
        "tagline": "Open-source image generation powerhouse",
        "description": "Stability AI's open-source model that can be run locally. Offers unmatched customization through LoRA models, ControlNet, and a massive ecosystem of fine-tuned variants and community tools.",
        "features": [
            "Open source & local",
            "LoRA fine-tuning",
            "ControlNet guidance",
            "Inpainting & img2img",
            "Massive model ecosystem",
            "No content restrictions locally",
        ],
        "pricing": "Free",
        "pricing_details": "Completely free to run locally. Cloud APIs available from various providers.",
        "website_url": "https://stability.ai",
        "rating": 4.6,
        "review_count": 9200,
        "is_featured": True,
        "category_slug": "image-generation",
    },
    {
        "name": "Leonardo.ai",
        "slug": "leonardo-ai",
        "tagline": "Professional AI image & asset generation",
        "description": "Leonardo.ai targets game developers, designers, and creative professionals with fine-tuned models for consistent character design, game assets, and production-ready imagery.",
        "features": [
            "Character consistency",
            "Game asset generation",
            "Real-time canvas",
            "Custom model training",
            "Motion generation",
            "API for developers",
        ],
        "pricing": "Freemium",
        "pricing_details": "Free 150 tokens/day. Apprentice $12/mo. Artisan $30/mo. Maestro $60/mo.",
        "website_url": "https://leonardo.ai",
        "rating": 4.4,
        "review_count": 4100,
        "is_featured": False,
        "category_slug": "image-generation",
    },
    # ── Code & Development ──
    {
        "name": "GitHub Copilot",
        "slug": "github-copilot",
        "tagline": "Your AI pair programmer",
        "description": "GitHub Copilot integrates directly into VS Code and other IDEs, suggesting whole lines and functions as you type. Trained on billions of lines of public code, it dramatically speeds up development.",
        "features": [
            "Inline code suggestions",
            "Chat within IDE",
            "Multi-file editing",
            "Test generation",
            "Documentation writing",
            "CLI assistant",
        ],
        "pricing": "Paid",
        "pricing_details": "Individual $10/mo. Business $19/user/mo. Enterprise $39/user/mo.",
        "website_url": "https://github.com/features/copilot",
        "rating": 4.6,
        "review_count": 13500,
        "is_featured": True,
        "category_slug": "code-development",
    },
    {
        "name": "Cursor",
        "slug": "cursor",
        "tagline": "The AI-first code editor",
        "description": "Cursor is a VS Code fork built around AI from the ground up. Features intelligent codebase-aware completions, inline edits via natural language, and deep context understanding across your entire project.",
        "features": [
            "Codebase-aware AI",
            "Inline natural language edits",
            "Multi-file refactoring",
            "Codebase chat",
            "Composer for multi-step tasks",
            "Privacy mode",
        ],
        "pricing": "Freemium",
        "pricing_details": "Free with limited AI. Pro $20/mo. Business $40/user/mo.",
        "website_url": "https://cursor.sh",
        "rating": 4.7,
        "review_count": 6800,
        "is_featured": True,
        "category_slug": "code-development",
    },
    {
        "name": "Tabnine",
        "slug": "tabnine",
        "tagline": "Privacy-first AI code assistant",
        "description": "Tabnine offers AI code completion with a strong emphasis on privacy. Can be run on-premises or on private cloud, ensuring your code never leaves your infrastructure. Supports 30+ languages.",
        "features": [
            "On-premise deployment",
            "Whole-line completion",
            "Private model training",
            "30+ languages",
            "IDE integration",
            "Enterprise security",
        ],
        "pricing": "Freemium",
        "pricing_details": "Free basic completion. Pro $12/mo. Enterprise custom pricing.",
        "website_url": "https://tabnine.com",
        "rating": 4.2,
        "review_count": 3200,
        "is_featured": False,
        "category_slug": "code-development",
    },
    {
        "name": "Replit AI",
        "slug": "replit-ai",
        "tagline": "Build software entirely in the browser",
        "description": "Replit combines a full cloud IDE with AI capabilities. Build, run, and deploy applications from your browser with AI assistance for code generation, debugging, and deployment.",
        "features": [
            "Cloud IDE",
            "AI code generation",
            "Instant deployment",
            "Collaborative editing",
            "Database hosting",
            "Custom domains",
        ],
        "pricing": "Freemium",
        "pricing_details": "Free tier available. Replit Core $25/mo with advanced AI features.",
        "website_url": "https://replit.com",
        "rating": 4.3,
        "review_count": 4500,
        "is_featured": False,
        "category_slug": "code-development",
    },
    # ── Video & Audio ──
    {
        "name": "Runway ML",
        "slug": "runway-ml",
        "tagline": "Next-generation video creation",
        "description": "Runway is the leading AI video platform, offering Gen-3 Alpha for text-to-video generation, plus tools for motion tracking, background removal, color grading, and more professional video editing features.",
        "features": [
            "Gen-3 text-to-video",
            "Motion brush",
            "Background removal",
            "Color grading",
            "Inpainting",
            "Frame interpolation",
        ],
        "pricing": "Freemium",
        "pricing_details": "Free limited credits. Standard $15/mo. Pro $35/mo. Unlimited $95/mo.",
        "website_url": "https://runwayml.com",
        "rating": 4.5,
        "review_count": 5800,
        "is_featured": True,
        "category_slug": "video-audio",
    },
    {
        "name": "ElevenLabs",
        "slug": "elevenlabs",
        "tagline": "Ultra-realistic AI voice synthesis",
        "description": "ElevenLabs produces the most natural-sounding AI voices available. Clone your voice, choose from a library of pre-made voices, and generate speech in 29 languages with emotional nuance and control.",
        "features": [
            "Voice cloning",
            "29 languages",
            "Emotional control",
            "Voice library",
            "API access",
            "Dubbing studio",
        ],
        "pricing": "Freemium",
        "pricing_details": "Free 10k chars/mo. Starter $5/mo. Pro $22/mo. Scale $99/mo.",
        "website_url": "https://elevenlabs.io",
        "rating": 4.7,
        "review_count": 7200,
        "is_featured": False,
        "category_slug": "video-audio",
    },
    {
        "name": "Descript",
        "slug": "descript",
        "tagline": "Edit video by editing text",
        "description": "Descript revolutionizes video editing by letting you edit media by editing a transcript. Remove filler words, clone your voice, add screen recordings, and collaborate — all in one tool.",
        "features": [
            "Text-based editing",
            "Filler word removal",
            "Voice cloning",
            "Screen recording",
            "Transcription",
            "Collaborative editing",
        ],
        "pricing": "Freemium",
        "pricing_details": "Free 1hr/mo. Hobby $24/mo. Pro $33/mo. Business $40/mo.",
        "website_url": "https://descript.com",
        "rating": 4.4,
        "review_count": 3900,
        "is_featured": False,
        "category_slug": "video-audio",
    },
    {
        "name": "Synthesia",
        "slug": "synthesia",
        "tagline": "AI video presentations without cameras",
        "description": "Synthesia creates professional videos with AI avatars. Choose from 160+ avatars, type your script, and produce training, marketing, or presentation videos in 130+ languages without any filming.",
        "features": [
            "160+ AI avatars",
            "130+ languages",
            "Custom avatar creation",
            "Template library",
            "Screen recording",
            "Team collaboration",
        ],
        "pricing": "Paid",
        "pricing_details": "Starter $29/mo. Creator $89/mo. Enterprise custom pricing.",
        "website_url": "https://synthesia.io",
        "rating": 4.3,
        "review_count": 2800,
        "is_featured": False,
        "category_slug": "video-audio",
    },
    # ── Productivity ──
    {
        "name": "Notion AI",
        "slug": "notion-ai",
        "tagline": "AI connected to all your knowledge",
        "description": "Notion AI is embedded directly into your workspace — summarize pages, generate content, extract action items, translate text, and brainstorm ideas without leaving your notes and docs.",
        "features": [
            "In-page AI assistant",
            "Summarization",
            "Action item extraction",
            "Translation",
            "Writing improvement",
            "Q&A over workspace",
        ],
        "pricing": "Paid",
        "pricing_details": "Add-on at $10/member/mo. Included in Business and Enterprise plans.",
        "website_url": "https://notion.so/product/ai",
        "rating": 4.5,
        "review_count": 6200,
        "is_featured": False,
        "category_slug": "productivity",
    },
    {
        "name": "Otter.ai",
        "slug": "otter-ai",
        "tagline": "Meeting notes that write themselves",
        "description": "Otter.ai provides real-time transcription for meetings, calls, and lectures. Automatically generates summaries, assigns action items, and integrates with Zoom, Google Meet, and Microsoft Teams.",
        "features": [
            "Real-time transcription",
            "Meeting summaries",
            "Action items",
            "Zoom/Meet integration",
            "Speaker identification",
            "Searchable archives",
        ],
        "pricing": "Freemium",
        "pricing_details": "Free 300 min/mo. Pro $16.99/mo. Business $30/user/mo. Enterprise custom.",
        "website_url": "https://otter.ai",
        "rating": 4.3,
        "review_count": 4100,
        "is_featured": False,
        "category_slug": "productivity",
    },
    {
        "name": "Grammarly",
        "slug": "grammarly",
        "tagline": "AI writing assistant everywhere you write",
        "description": "Grammarly goes beyond grammar checking with AI-powered writing suggestions for clarity, tone, and style. Works across browsers, email, documents, and social platforms with context-aware assistance.",
        "features": [
            "Grammar & spelling",
            "Tone detection",
            "Clarity suggestions",
            "Plagiarism detection",
            "Browser extension",
            "Style guide enforcement",
        ],
        "pricing": "Freemium",
        "pricing_details": "Free basic. Premium $12/mo. Business $15/member/mo.",
        "website_url": "https://grammarly.com",
        "rating": 4.5,
        "review_count": 14500,
        "is_featured": True,
        "category_slug": "productivity",
    },
    {
        "name": "Mem.ai",
        "slug": "mem-ai",
        "tagline": "Self-organizing AI workspace",
        "description": "Mem is an AI-powered note-taking app that automatically organizes your notes, surfaces relevant information, and connects ideas across your knowledge base without manual tagging or filing.",
        "features": [
            "Auto-organization",
            "AI search",
            "Knowledge graph",
            "Daily briefings",
            "Smart collections",
            "API access",
        ],
        "pricing": "Paid",
        "pricing_details": "Mem X at $14.99/mo. Business at $19/user/mo.",
        "website_url": "https://mem.ai",
        "rating": 4.1,
        "review_count": 1800,
        "is_featured": False,
        "category_slug": "productivity",
    },
    # ── Data & Analytics ──
    {
        "name": "Julius AI",
        "slug": "julius-ai",
        "tagline": "Data analysis in plain English",
        "description": "Julius AI lets you upload datasets and analyze them using natural language. Generate visualizations, run statistical tests, build predictive models, and export reports — all through conversation.",
        "features": [
            "Natural language queries",
            "Auto-visualization",
            "Statistical analysis",
            "Predictive modeling",
            "Data cleaning",
            "Export to multiple formats",
        ],
        "pricing": "Freemium",
        "pricing_details": "Free basic queries. Lite $20/mo. Pro $40/mo. Elite custom pricing.",
        "website_url": "https://julius.ai",
        "rating": 4.4,
        "review_count": 2100,
        "is_featured": False,
        "category_slug": "data-analytics",
    },
    {
        "name": "Tableau AI",
        "slug": "tableau-ai",
        "tagline": "AI-powered visual analytics at enterprise scale",
        "description": "Tableau's AI features include natural language queries, automated insight discovery, and smart data preparation. Part of the Salesforce ecosystem, it brings AI to enterprise BI workflows.",
        "features": [
            "Natural language queries",
            "Ask Data",
            "Explain Data",
            "Auto-visualizations",
            "Enterprise governance",
            "Salesforce integration",
        ],
        "pricing": "Paid",
        "pricing_details": "Viewer $15/user/mo. Explorer $42/user/mo. Creator $70/user/mo.",
        "website_url": "https://tableau.com",
        "rating": 4.5,
        "review_count": 8900,
        "is_featured": False,
        "category_slug": "data-analytics",
    },
    {
        "name": "MonkeyLearn",
        "slug": "monkeylearn",
        "tagline": "No-code text analytics platform",
        "description": "MonkeyLearn provides no-code AI models for text classification, sentiment analysis, and keyword extraction. Connect data sources, train custom models, and visualize results without writing code.",
        "features": [
            "Text classification",
            "Sentiment analysis",
            "Keyword extraction",
            "No-code model training",
            "Data connectors",
            "REST API",
        ],
        "pricing": "Paid",
        "pricing_details": "Starter $299/mo. Team $599/mo. Enterprise custom.",
        "website_url": "https://monkeylearn.com",
        "rating": 4.2,
        "review_count": 1200,
        "is_featured": False,
        "category_slug": "data-analytics",
    },
    {
        "name": "Polymer",
        "slug": "polymer",
        "tagline": "Spreadsheet data, AI-powered insights",
        "description": "Polymer transforms spreadsheets into interactive dashboards with AI. Upload CSV/Excel data and get automated visualizations, insights, and a shareable dashboard in seconds without formulas or pivot tables.",
        "features": [
            "Auto-visualization",
            "AI insights",
            "Spreadsheet import",
            "Interactive dashboards",
            "Sharing & embedding",
            "Data cleaning",
        ],
        "pricing": "Freemium",
        "pricing_details": "Free basic. Pro $20/mo. Business custom pricing.",
        "website_url": "https://polymersearch.com",
        "rating": 4.1,
        "review_count": 950,
        "is_featured": False,
        "category_slug": "data-analytics",
    },
    # ── Design ──
    {
        "name": "Figma AI",
        "slug": "figma-ai",
        "tagline": "AI design features in your workflow",
        "description": "Figma's AI capabilities include auto-layout suggestions, content generation for mockups, image generation, and design system recommendations — all integrated into the world's most popular design tool.",
        "features": [
            "Auto layout AI",
            "Content generation",
            "Image fill",
            "Design system suggestions",
            "Layer renaming",
            "Variable modes",
        ],
        "pricing": "Freemium",
        "pricing_details": "Free for 3 files. Professional $15/editor/mo. Organization $45/editor/mo.",
        "website_url": "https://figma.com",
        "rating": 4.6,
        "review_count": 10200,
        "is_featured": True,
        "category_slug": "design",
    },
    {
        "name": "Canva AI",
        "slug": "canva-ai",
        "tagline": "Design anything with AI assistance",
        "description": "Canva's Magic Studio suite brings AI to everyday design — generate images, remove backgrounds, rewrite text, create presentations from prompts, and design complete brand kits automatically.",
        "features": [
            "Magic Design",
            "Background remover",
            "Text to image",
            "Magic Write",
            "Brand kit generator",
            "Presentation builder",
        ],
        "pricing": "Freemium",
        "pricing_details": "Free basic. Pro $14.99/mo. Teams $29.99/mo. Enterprise custom.",
        "website_url": "https://canva.com",
        "rating": 4.6,
        "review_count": 16800,
        "is_featured": False,
        "category_slug": "design",
    },
    {
        "name": "Adobe Firefly",
        "slug": "adobe-firefly",
        "tagline": "Commercially safe generative AI",
        "description": "Adobe Firefly is trained on licensed content, making it safe for commercial use. Integrated into Photoshop, Illustrator, and Express, it generates images, applies effects, and extends images responsibly.",
        "features": [
            "Commercially safe training",
            "Photoshop integration",
            "Generative fill",
            "Text effects",
            "Recolor vectors",
            "3D to image",
        ],
        "pricing": "Freemium",
        "pricing_details": "25 free credits/mo. Premium $4.99/mo. Included in Creative Cloud.",
        "website_url": "https://firefly.adobe.com",
        "rating": 4.4,
        "review_count": 5400,
        "is_featured": False,
        "category_slug": "design",
    },
    {
        "name": "Khroma",
        "slug": "khroma",
        "tagline": "AI color palette generator tailored to you",
        "description": "Khroma uses AI to learn your color preferences and generates endless palettes, gradients, and typography combinations you'll actually love. Train it by choosing colors and it gets smarter over time.",
        "features": [
            "Personalized palettes",
            "Gradient generation",
            "Typography pairings",
            "Color blindness simulation",
            "Infinite generation",
            "Copy CSS/JSON",
        ],
        "pricing": "Free",
        "pricing_details": "Completely free to use. No account required.",
        "website_url": "https://khroma.co",
        "rating": 4.0,
        "review_count": 780,
        "is_featured": False,
        "category_slug": "design",
    },
    # ── Customer Support ──
    {
        "name": "Intercom Fin",
        "slug": "intercom-fin",
        "tagline": "AI agent that resolves 50% of support",
        "description": "Intercom Fin is an AI customer service agent that answers questions, resolves issues, and escalates complex cases to human agents. Built on GPT-4 with full context from your help center and past conversations.",
        "features": [
            "Autonomous resolution",
            "Help center learning",
            "Human handoff",
            "Multi-language",
            "Custom workflows",
            "Analytics & reporting",
        ],
        "pricing": "Paid",
        "pricing_details": "Included in Intercom plans starting at $39/seat/mo. Fin usage billed separately.",
        "website_url": "https://intercom.com/fin",
        "rating": 4.5,
        "review_count": 3400,
        "is_featured": False,
        "category_slug": "customer-support",
    },
    {
        "name": "Chatbase",
        "slug": "chatbase",
        "tagline": "Custom AI chatbot from your data",
        "description": "Upload your website URL, PDFs, or text and Chatbase creates a custom GPT-powered chatbot trained on your content. Embed it on your site to answer customer questions 24/7.",
        "features": [
            "Custom data training",
            "Website embedding",
            "PDF upload",
            "Lead collection",
            "Multi-language",
            "Analytics dashboard",
        ],
        "pricing": "Freemium",
        "pricing_details": "Free 30 messages/mo. Lite $19/mo. Pro $99/mo. Unlimited $399/mo.",
        "website_url": "https://chatbase.co",
        "rating": 4.2,
        "review_count": 2600,
        "is_featured": False,
        "category_slug": "customer-support",
    },
    {
        "name": "Tidio AI",
        "slug": "tidio-ai",
        "tagline": "Live chat supercharged with AI",
        "description": "Tidio combines live chat, chatbot, and AI capabilities for small businesses. Its AI (Lyro) resolves customer questions automatically using your content, while humans handle complex issues.",
        "features": [
            "AI chatbot (Lyro)",
            "Live chat",
            "Helpdesk",
            "Shopify/WooCommerce integration",
            "Multi-channel",
            "Visitor tracking",
        ],
        "pricing": "Freemium",
        "pricing_details": "Free 50 conversations/mo. Starter $29/mo. Growth $59/mo.",
        "website_url": "https://tidio.com",
        "rating": 4.3,
        "review_count": 3100,
        "is_featured": False,
        "category_slug": "customer-support",
    },
    {
        "name": "Zoho Zia",
        "slug": "zoho-zia",
        "tagline": "AI assistant across the Zoho suite",
        "description": "Zia is Zoho's AI assistant embedded across 50+ Zoho applications. It provides sentiment analysis, anomaly detection, predictive analytics, and natural language querying across your business data.",
        "features": [
            "Sentiment analysis",
            "Anomaly detection",
            "Predictive analytics",
            "Natural language queries",
            "Zoho ecosystem integration",
            "Automated workflows",
        ],
        "pricing": "Paid",
        "pricing_details": "Included with Zoho CRM Plus ($50/user/mo) and Enterprise plans.",
        "website_url": "https://zoho.com/zia",
        "rating": 4.1,
        "review_count": 1900,
        "is_featured": False,
        "category_slug": "customer-support",
    },
]


def seed():
    import os

    db_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "instance", "ai_tools.db")
    )
    uri = "sqlite:///" + db_path

    class SeedConfig(Config):
        SQLALCHEMY_DATABASE_URI = uri

    app = create_app(SeedConfig)
    with app.app_context():
        if Tool.query.first() is not None:
            print("Database already seeded. Skipping.")
            return

        # Create categories
        cat_map = {}
        for cat_data in CATEGORIES:
            cat = Category(**cat_data)
            db.session.add(cat)
            db.session.flush()
            cat_map[cat.slug] = cat.id

        # Create tools
        for tool_data in TOOLS:
            cat_slug = tool_data.pop("category_slug")
            tool_data["category_id"] = cat_map[cat_slug]
            tool_data["features"] = json.dumps(tool_data["features"])
            tool = Tool(**tool_data)
            db.session.add(tool)

        db.session.commit()
        print(f"Seeded {len(CATEGORIES)} categories and {len(TOOLS)} tools.")


if __name__ == "__main__":
    seed()
